################################################################
#     _______  _                 _______  _______  _______     #
#    (  ____ \| \    /\|\     /|(  ____ \(  ____ \(  ___  )    #
#    | (    \/|  \  / /( \   / )| (    \/| (    \/| (   ) |    #
#    | (_____ |  (_/ /  \ (_) / | (__    | (__    | (___) |    #
#    (_____  )|   _ (    \   /  |  __)   |  __)   |  ___  |    #
#          ) ||  ( \ \    ) (   | (      | (      | (   ) |    #
#    /\____) ||  /  \ \   | |   | )      | )      | )   ( |    #
#    \_______)|_/    \/   \_/   |/       |/       |/     \|    #
#                                                              #
#              Made with love for TheJokerDev <3               #
################################################################

#Configuration (lang_REGION)
language: en_US
debug: false

spawn:

options:
  forceSpawn: true
  orderedSpawnPoints: true
  saveInventory: true
  perWorldTabBypass: true
  weather: false